### ISSUE TITLE
Whether there will be false positives in the new call sequence generated after the mutation of the graph.

### ISSUE THREAD

**Issue by aT0ngMu** [hgarrereyn/GraphFuzz#18]
Thank you very much for open-sourcing the tool !! 
In the process of learning Graphfuzz, I have a question to consult with you.

That is, is there a possibility of false positives in the newly generated call sequence after mutating the graph?

For example, the original call sequence is A->B->C. After mutating the graph by removing node B, the mutated call sequence becomes A->C. However, in a real project usage scenario, it is necessary to call B before calling C; otherwise, an error will occur. This error is due to improper API usage caused by the graph mutation, and it is not a result of an internal logic error in the tested function. In other words, it is a false positive.

Has Graphfuzz taken this situation into account and how does it handle this issue?

Once again, thank you for reaching out, and I anticipate our future discussions with enthusiasm.

**Comment by NikLeberg** [comment]
Hi there @aT0ngMu, I'm not @hgarrereyn but maybe can help. If your API returns a specific error because it was not called correctly you may check for and handle it. See example [here](https://github.com/hgarrereyn/GraphFuzz/blob/1894510f75b07f3ffcf4c59076a468f9c59316c2/experiments/iowow/in/f1/schema.yaml#L122) where the function `graphfuzz_bail()` is used to mark a false positive. At least that is how I understood and used that GraphFuzz API.

**Comment by hgarrereyn** [comment]
Hi @aT0ngMu thanks for reaching out! As @NikLeberg mentioned, you can use `graphfuzz_bail` to suppress false positives that are detected during execution. This feature is sort of undocumented but can be used if you are able to detect that a fatal error has occurred during runtime and you want to ignore it. However, in the case you are describing, there are some nicer ways to handle it, see below:

It is possible for GraphFuzz to generate false positives like you described. As an example API:
```cpp
struct Foo {
    bool initialized;

    Foo() { initialized = false; }
    void setup() { initialized = true; }
    void bar() {
        assert(initialized);
        // do thing...
    }
};
```

Here it is required to call `setup()` before anything else.

So this is allowed:
```cpp
Foo *f = new Foo();
f->setup();
f->bar();
delete f;
```
But this is not allowed:
```cpp
Foo *f = new Foo();
f->bar();
delete f;
```

---

By default GraphFuzz does not know that `setup()` is required, however there are at least two ways to enforce this and prevent false positives:

### 1. Define a custom initialization routine:

If the object you are trying to use _always_ requires invoking some setup method, you can directly enforce that by defining a custom constructor like the following:

```yaml
Foo:
  type: struct
  name: Foo
  headers: [demo.h]
  methods:
  - Foo():
      outputs: ['Foo']
      exec: |
        $o0 = new Foo();
        $o0->setup();
  - void bar()
```

Here, the only valid way to construct a `Foo` also requires invoking `Foo::setup`.

### 2. Define pseudo-types

An alternative is to define some new pseudo-types that represent a `Foo` object in different states. In this case, for example you could do `Foo_uninitialized` and `Foo_initialized` to mark the two different states.

```yaml
Foo_uninitialized:
  type: struct
  name: Foo_uninitialized
  headers: [demo.h]
  default_destructor: true
  methods:
  - Foo():
      outputs: ['Foo_uninitialized']
      exec: |
        $o0 = new Foo();
  - setup():
      inputs: ['Foo_uninitialized']
      outputs: ['Foo_initialized']
      exec: |
        $i0->setup();
        $o0 = $i0;

Foo_initialized:
  type: struct
  name: Foo_initialized
  headers: [demo.h]
  default_destructor: true
  methods:
  - void bar()
```

And include these typedefs in a header:

```cpp
typedef Foo Foo_initialized;
typedef Foo Foo_uninitialized;
```

Here, the only way to call `bar` is on a `Foo_initialized` object. And that can only be constructed by first creating a `Foo_uninitialized` object and calling `setup`.
